### ISSUE TITLE
Add User Profile Backend Integration 

### ISSUE THREAD

**Issue by sshaik03** [MominHumayon/326FinalProject#17]
Purpose
This issue focuses on implementing the backend functionality for handling user profiles. Specifically:

Save user profile data to the SQLite database via a POST request.
Verify user profiles via a GET request using first and last names (case-insensitive).

Key Tasks
Set up the SQLite database and define the Sequelize model (Users) with fields:
firstName, lastName, heightFeet, heightInches, weight, and diet.
Create the POST /api/user endpoint for saving user profiles to the database.
Create the GET /api/user endpoint for verifying users by their names (case-insensitive).
Update front-end logic for the Save Profile and Login buttons to interact with the backend endpoints.
Add error handling for invalid or missing data.

Testing
Verified the POST and GET endpoints via Postman and cURL to confirm proper database functionality.
Tested case-insensitivity in user verification during login.
Basic front-end integration tested for interaction with backend endpoints.

Labels
backend
feature

Assignee: Sameen

**Comment by adithya-anand-999** [comment]
I like your breakdown of the POST and GET requests you did. The attributes we collect now are good but in the future we could look to collect more so we can create a more sound meal recommender. Your testing looks like it covers everything but I think we should maybe do more tests, in the future I think this is something we could do later.

**Comment by sshaik03** [comment]
Closed by #31
