### ISSUE TITLE
Scrapping Get_Mobile 

### ISSUE THREAD

**Issue by adithya-anand-999** [MominHumayon/326FinalProject#19]
Scrape information from get, this is done on the website not the mobile app. 

Large feature

Key tasks

* Navigate to the URL https://get.cbord.com/umass/full/prelogin.php
* Preform a login with users information, is inteneded to be fully automatic. But securty features from Microsoft OAuth wont allow this to happen. So it is semi-automatic. 
* Scrape the information we need (UCard Swipes and Debit Balance)
* Scrape the information about history of usage.
* Store the information in a database 
* Add a visualization of the history so user can see how their UCard and Debit balance has changed in the past 7 days. 

Assignee: Adithya

**Comment by MominHumayon** [comment]
Perhaps consider dining dollars as well, maybe guest swipes. 

Also, you can wipe history that is older than 7 days

**Comment by adithya-anand-999** [comment]
it was implemented, could not add feature for history
