### ISSUE TITLE
Getting past Microsoft OAuth for scrapping get mobile 

### ISSUE THREAD

**Issue by adithya-anand-999** [MominHumayon/326FinalProject#20]
The issue around filling in users password and email for get mobile, current issue is around navigating the process. Having issues with getting stuck on navigating past the password login page.

**Comment by MominHumayon** [comment]
If nothing else works, we might ask the user to input their password upon profile creation

**Comment by adithya-anand-999** [comment]
yes that was the way it had to be done after some research, Microsoft OAuth does not allow a fully integrated setup without some crazy additional work that I did not have the time for. In the future this could be something we can do. It would involve getting the users phone number and receiving texts from it automatically. I doubt it would be easy or even something I would want to do, seems like a overstep into users privacy.
