### ISSUE TITLE
Scraping Meal Information from UMass Dining

### ISSUE THREAD

**Issue by MominHumayon** [MominHumayon/326FinalProject#21]
Scrape information from UMass Dining Website

Large feature (turns out actually ASTRONOMICALLY GARGANTUAN)

Key tasks
1. Fetch from UMass Dining based on input parameters
2. Parse information to extract relevant details
3. Store information to database
4. Deliver information to frontend for display, upon request from dining hall selector OR meal recommender

Assignee: Momin

**Comment by akchdhry** [comment]
I suggest Puppeteer, scraping can be done easily using puppeteer and can be used by typing into the console "npm install puppeteer"

**Comment by MominHumayon** [comment]
Closed with #34
