### ISSUE TITLE
Implement backend for goal tracker

### ISSUE THREAD

**Issue by tawsifazad23** [MominHumayon/326FinalProject#24]
Implement backend for goal tracker

**Comment by Yraz60** [comment]
Need more detail.
what is being stored, and what is being done from that data.
where are you retrieving that data from?

good work Tawsif

**Comment by tawsifazad23** [comment]
What is being stored:
We are storing user-specific dietary goals (e.g., calories, protein, carbs, fat targets) along with meal-related data such as nutritional information, allergen info, and dining hall availability. This includes meal details like calories, carbs, protein, and fat, which are critical for tracking goal progress.

What is being done with the data:
The user's dietary goals are used to compare their daily and weekly meal intake against their targets. The backend will aggregate nutritional data from meals selected by the user and calculate how close they are to meeting their goals (e.g., a progress bar showing calorie intake as a percentage of the daily target). The scraped meal data enhances this by allowing users to explore meal options and select items that align with their goals.

Where the data is being retrieved from:

User Goal Data: Input by users when they set their goals (e.g., bulking, cutting, or maintenance).
Meal Data: Retrieved from a combination of predefined datasets, scraped images, and additional metadata fetched from APIs. This ensures the user has up-to-date and detailed meal options for tracking their progress.

**Comment by tawsifazad23** [comment]
closed by #26

**Comment by tawsifazad23** [comment]
closed by #26
