### ISSUE TITLE
implement backend for graphs

### ISSUE THREAD

**Issue by Yraz60** [MominHumayon/326FinalProject#25]
Backend from graph page

Large Feature

Key Tasks
1.Retrieve Calorie and nutrient information from meal selection
2. Store Calorie in database
3. Store Nutrient amount in database
4. use Calorie and nutrient information to update bar and pie graphs

**Comment by sshaik03** [comment]
How will the backend provide the data needed for graphs in a structured way? I think you can define endpoints to retrieve weekly calorie trends and nutrient breakdowns in a format that front end can display in an easy way. Nice work Yusuf Raza!

**Comment by ahmedar04** [comment]
Need clarification on data storage approach for implementing graphs:

Are we storing meal history in SQLite or should we use another solution?
Which specific graphs are needed (weekly calories, nutrient breakdown)?
How long should we retain meal history data?

Happy to provide more implementation details once these are clarified. Good Work!
