### ISSUE TITLE
Implemented backend meal recommender

### ISSUE THREAD

**Issue by ahmedar04** [MominHumayon/326FinalProject#29]
# UMass Dining Meal Recommender - Large Feature

A personalized meal recommendation system for UMass dining halls that helps students find meals matching their dietary preferences and sustainability goals.

## Key Features

- Personalized recommendations based on dietary preferences (vegetarian, plant-based, halal, whole grain)
- Filtering options for locally-sourced and sustainable meals
- Real-time nutrition information including calories, protein, and carbs
- Carbon rating system (A-D) to help make environmentally conscious choices
- Support for all major dining locations: Worcester, Franklin, Hampshire, and Berkshire

## Technical Implementation

- Real-time data scraping from UMass dining menus
- Dynamic UI updates based on user preferences
- Nutrition tracking and visualization
- Mobile-responsive design

## Data Sources
- Live menu data from UMass Dining website
- Nutritional information for each meal
- Sustainability and sourcing information
- Carbon footprint ratings

The system helps students make informed dining choices while considering both their nutritional needs and environmental impact.

**Comment by sshaik03** [comment]
I like the ideas that you have. If you need help with scraping I would suggest Beautiful Soup.
